name: meonghae_front
description: 애완동물 스케줄 관리를 위한 어플리케이션
publish_to:

version: 2.0.4+11

environment:
  sdk: ">=3.0.0-322.0.dev <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  video_player: ^2.6.1
  kakao_flutter_sdk_user: ^1.4.2
  image_picker: ^0.8.4+4
  font_awesome_flutter: ^9.2.0
  carousel_slider: ^4.2.1
  table_calendar: ^3.0.9
  intl: ^0.18.1
  flutter_svg: ^2.0.6
  file_picker: ^4.0.0
  flutter_rating_stars: ^1.0.3+4
  dotted_border: ^2.0.0+3
  dio: ^5.2.0+1
  flutter_holo_date_picker: ^1.1.0
  flutter_time_picker_spinner: ^2.0.0
  flutter_spinner_picker: ^0.0.7
  flutter_datetime_picker: ^1.5.1
  spinner_date_time_picker: ^0.0.8
  flutter_secure_storage: ^8.0.0
  device_info: ^2.0.3
  equatable: ^2.0.5
  get: ^4.6.5
  flutter_local_notifications: ^8.2.0
  firebase_core: ^2.24.0
  firebase_messaging: ^14.7.3
  flutter_spinkit: ^5.2.0
  pull_to_refresh: ^2.0.0
  kakao_flutter_sdk: ^1.8.0
  cached_network_image: ^3.3.0
  path_provider: ^2.0.15
  langchain: ^0.3.1+1
  langchain_openai: ^0.3.1+1
  flutter_email_sender: ^6.0.2
  flutter_dotenv: ^5.1.0
  curved_navigation_bar: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/logo/
    - assets/images/dog_pictures/
    - assets/videos/

  fonts:
    - family: GmarketSans
      fonts:
        - asset: assets/fonts/GmarketSansTTFMedium.ttf
        - asset: assets/fonts/GmarketSansTTFMedium.ttf
        - asset: assets/fonts/GmarketSansTTFLight.ttf
